### ISSUE TITLE
Enable VM Insights Guest Health (Preview)

### ISSUE THREAD

**Issue by joshuawaddell** [azuredemoenvironment/ade#123]
https://docs.microsoft.com/en-us/azure/azure-monitor/vm/vminsights-health-enable?tabs=powershell

**Comment by brandonmartinez** [comment]
It seems like there's still uncertainty on _how_ this should be implemented. E.g., https://docs.microsoft.com/en-us/azure/azure-monitor/vm/vminsights-health-migrate

Hold off for now.

**Comment by joshuawaddell** [comment]
Implemented in #189. Closed.
