### ISSUE TITLE
Using loadText() is currently not an option for BICEP Script Extensions.  Conversation pasted here:

### ISSUE THREAD

**Issue by nandrespersonal** [azuredemoenvironment/ade#153]
Using loadText() is currently not an option for BICEP Script Extensions.  Conversation pasted here:

[Yesterday 12:45 PM] Nick Andres
    hey Brandon Martinez or Joshua Waddell, I'm kind of stuck trying to make this work. 
Are there any examples where custom script extensions actually reference a 'loadTextContent' variable?  I can't seem to find examples where this works

​[Yesterday 12:45 PM] Joshua Waddell
    let me look

​[Yesterday 12:47 PM] Nick Andres
it seems like all Custom Script Extensions I'm looking at always expects a 'fileUris'

[Yesterday 2:10 PM] Brandon Martinez
    Nick Andres so it sounds like I sent you on a wild goose chase speechless finally got out of customer calls and synced with Josh, doesn't look like we'll be able to do that sad

​[Yesterday 2:10 PM] Brandon Martinez
    Thank you for spending time in research and clarifying it

_Originally posted by @nandrespersonal in https://github.com/joshuawaddell/azure-demo-environment/issues/146#issuecomment-943668994_

**Comment by brandonmartinez** [comment]
Solved with passing in scriptsBaseUri to ade.ps1 to allow for non-default script locations during development.
