### ISSUE TITLE
Update Location Variable to a Parameter

### ISSUE THREAD

**Issue by joshuawaddell** [azuredemoenvironment/ade#182]
Recent updates to the linting feature in the Bicep tooling now requires location values and functions to exist as parameters as opposed to variables. Adjust all files as necessary.

**Comment by brandonmartinez** [comment]
Change this:

```bicep
var location = resourceGroup().location
```

To this in the header of the file:

```bicep
@description('The Azure region to deploy the resources to.')
param location string = resourceGroup().location
```

@joshuawaddell  thoughts on the description?

**Comment by brandonmartinez** [comment]
@CurtisJWilson if there are any locations that reference `global`, you can remove the variable/parameter and then type `global` inline instead (you should be able to just fix the errors after you delete the variable/parameter).

Example:

```bicep
var location = 'global'

/// other code

resource budgetActionGroup 'microsoft.insights/actionGroups@2019-06-01' = {
  name: budgetActionGroupName
  location: location
  // other params
}
```

To this:

```bicep
resource budgetActionGroup 'microsoft.insights/actionGroups@2019-06-01' = {
  name: budgetActionGroupName
  location: 'global'
  // other params
}
```

**Comment by joshuawaddell** [comment]
This has been completed.
