### ISSUE TITLE
Customizable Region Support

### ISSUE THREAD

**Issue by brandonmartinez** [azuredemoenvironment/ade#72]
Allow the user to specify which region the user can deploy into. This could either be any region the user wants, or have suggested region-pairs. Or, have the user choose the primary region and we pick the secondary region as a supported pair.

**Comment by fskelly** [comment]
Start working on an example region picker - currently has region-short function in the gist - https://gist.github.com/fskelly/412668da84d6a4307cdbaf023080e34c

**Comment by brandonmartinez** [comment]
Adding a link to another gist by @fskelly, this one allows the picked region to be short-coded in bicep:

https://gist.github.com/fskelly/c3917ccbb06f6841339f65f2aef6b1f3

**Comment by brandonmartinez** [comment]
@nandrespersonal add this to the `/login.ps1` at the very end:

<img width="925" alt="image" src="https://user-images.githubusercontent.com/32435/137329316-789f8a63-c176-4640-b05d-18070447ae4f.png">

After the user has finished all of their login activities, prompt them to pick a region using fskelly's PowerShell script above (specifically, lines `19` - `37`). I think the easiest way to use it would be to capture it as an environment variable (you could call it something like `ade-selected-region`).

This could then be used during the `deploy` or other tasks by grabbing that newly set variable, and then we can leave the shortcode detection to bicep using the second script from fskelly I posted above (we may create another issue for that… let's see how that goes).

**Comment by brandonmartinez** [comment]
We'll need to remove any hard coded references to "EastUS" "East EUS" "eus" or corresponding "West US".

@caschw this is the issue we were discussing.
